/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/imagestream-resource/pkg/apis/openshift/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImagestreamResources implements ImagestreamResourceInterface
type FakeImagestreamResources struct {
	Fake *FakeOpenshiftV1alpha1
	ns   string
}

var imagestreamresourcesResource = schema.GroupVersionResource{Group: "openshift.tekton.dev", Version: "v1alpha1", Resource: "imagestreamresources"}

var imagestreamresourcesKind = schema.GroupVersionKind{Group: "openshift.tekton.dev", Version: "v1alpha1", Kind: "ImagestreamResource"}

// Get takes name of the imagestreamResource, and returns the corresponding imagestreamResource object, and an error if there is any.
func (c *FakeImagestreamResources) Get(name string, options v1.GetOptions) (result *v1alpha1.ImagestreamResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagestreamresourcesResource, c.ns, name), &v1alpha1.ImagestreamResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImagestreamResource), err
}

// List takes label and field selectors, and returns the list of ImagestreamResources that match those selectors.
func (c *FakeImagestreamResources) List(opts v1.ListOptions) (result *v1alpha1.ImagestreamResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagestreamresourcesResource, imagestreamresourcesKind, c.ns, opts), &v1alpha1.ImagestreamResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ImagestreamResourceList{ListMeta: obj.(*v1alpha1.ImagestreamResourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ImagestreamResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imagestreamResources.
func (c *FakeImagestreamResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagestreamresourcesResource, c.ns, opts))

}

// Create takes the representation of a imagestreamResource and creates it.  Returns the server's representation of the imagestreamResource, and an error, if there is any.
func (c *FakeImagestreamResources) Create(imagestreamResource *v1alpha1.ImagestreamResource) (result *v1alpha1.ImagestreamResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagestreamresourcesResource, c.ns, imagestreamResource), &v1alpha1.ImagestreamResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImagestreamResource), err
}

// Update takes the representation of a imagestreamResource and updates it. Returns the server's representation of the imagestreamResource, and an error, if there is any.
func (c *FakeImagestreamResources) Update(imagestreamResource *v1alpha1.ImagestreamResource) (result *v1alpha1.ImagestreamResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagestreamresourcesResource, c.ns, imagestreamResource), &v1alpha1.ImagestreamResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImagestreamResource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImagestreamResources) UpdateStatus(imagestreamResource *v1alpha1.ImagestreamResource) (*v1alpha1.ImagestreamResource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(imagestreamresourcesResource, "status", c.ns, imagestreamResource), &v1alpha1.ImagestreamResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImagestreamResource), err
}

// Delete takes name of the imagestreamResource and deletes it. Returns an error if one occurs.
func (c *FakeImagestreamResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(imagestreamresourcesResource, c.ns, name), &v1alpha1.ImagestreamResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImagestreamResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagestreamresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ImagestreamResourceList{})
	return err
}

// Patch applies the patch and returns the patched imagestreamResource.
func (c *FakeImagestreamResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImagestreamResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagestreamresourcesResource, c.ns, name, data, subresources...), &v1alpha1.ImagestreamResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImagestreamResource), err
}
