apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagestream-resource
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["openshift.tekton.dev"]
    resources: ["*"]
    verbs: ["*"]
