apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: openshift-pipelines
  labels:
    samples.knative.dev/release: devel

data:
  metrics.backend-destination: prometheus
  metrics.request-metrics-backend-destination: prometheus
  metrics.stackdriver-project-id: "<your stackdriver project id>"
  metrics.allow-stackdriver-custom-metrics: "false"
