apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: openshift-pipelines
  labels:
    samples.knative.dev/release: devel

data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
  # Log level overrides
  # Changes are be picked up immediately.
  loglevel.controller: "info"
  loglevel.webhook: "info"
