/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	openshiftv1alpha1 "github.com/openshift/imagestream-resource/pkg/apis/openshift/v1alpha1"
	versioned "github.com/openshift/imagestream-resource/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openshift/imagestream-resource/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openshift/imagestream-resource/pkg/client/listers/openshift/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ImagestreamResourceInformer provides access to a shared informer and lister for
// ImagestreamResources.
type ImagestreamResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ImagestreamResourceLister
}

type imagestreamResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewImagestreamResourceInformer constructs a new informer for ImagestreamResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewImagestreamResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredImagestreamResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredImagestreamResourceInformer constructs a new informer for ImagestreamResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredImagestreamResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenshiftV1alpha1().ImagestreamResources(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OpenshiftV1alpha1().ImagestreamResources(namespace).Watch(options)
			},
		},
		&openshiftv1alpha1.ImagestreamResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *imagestreamResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredImagestreamResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *imagestreamResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&openshiftv1alpha1.ImagestreamResource{}, f.defaultInformer)
}

func (f *imagestreamResourceInformer) Lister() v1alpha1.ImagestreamResourceLister {
	return v1alpha1.NewImagestreamResourceLister(f.Informer().GetIndexer())
}
