/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/openshift/imagestream-resource/pkg/apis/openshift/v1alpha1"
	scheme "github.com/openshift/imagestream-resource/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ImagestreamResourcesGetter has a method to return a ImagestreamResourceInterface.
// A group's client should implement this interface.
type ImagestreamResourcesGetter interface {
	ImagestreamResources(namespace string) ImagestreamResourceInterface
}

// ImagestreamResourceInterface has methods to work with ImagestreamResource resources.
type ImagestreamResourceInterface interface {
	Create(*v1alpha1.ImagestreamResource) (*v1alpha1.ImagestreamResource, error)
	Update(*v1alpha1.ImagestreamResource) (*v1alpha1.ImagestreamResource, error)
	UpdateStatus(*v1alpha1.ImagestreamResource) (*v1alpha1.ImagestreamResource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ImagestreamResource, error)
	List(opts v1.ListOptions) (*v1alpha1.ImagestreamResourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImagestreamResource, err error)
	ImagestreamResourceExpansion
}

// imagestreamResources implements ImagestreamResourceInterface
type imagestreamResources struct {
	client rest.Interface
	ns     string
}

// newImagestreamResources returns a ImagestreamResources
func newImagestreamResources(c *OpenshiftV1alpha1Client, namespace string) *imagestreamResources {
	return &imagestreamResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imagestreamResource, and returns the corresponding imagestreamResource object, and an error if there is any.
func (c *imagestreamResources) Get(name string, options v1.GetOptions) (result *v1alpha1.ImagestreamResource, err error) {
	result = &v1alpha1.ImagestreamResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagestreamresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImagestreamResources that match those selectors.
func (c *imagestreamResources) List(opts v1.ListOptions) (result *v1alpha1.ImagestreamResourceList, err error) {
	result = &v1alpha1.ImagestreamResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagestreamresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imagestreamResources.
func (c *imagestreamResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagestreamresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a imagestreamResource and creates it.  Returns the server's representation of the imagestreamResource, and an error, if there is any.
func (c *imagestreamResources) Create(imagestreamResource *v1alpha1.ImagestreamResource) (result *v1alpha1.ImagestreamResource, err error) {
	result = &v1alpha1.ImagestreamResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagestreamresources").
		Body(imagestreamResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a imagestreamResource and updates it. Returns the server's representation of the imagestreamResource, and an error, if there is any.
func (c *imagestreamResources) Update(imagestreamResource *v1alpha1.ImagestreamResource) (result *v1alpha1.ImagestreamResource, err error) {
	result = &v1alpha1.ImagestreamResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagestreamresources").
		Name(imagestreamResource.Name).
		Body(imagestreamResource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *imagestreamResources) UpdateStatus(imagestreamResource *v1alpha1.ImagestreamResource) (result *v1alpha1.ImagestreamResource, err error) {
	result = &v1alpha1.ImagestreamResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagestreamresources").
		Name(imagestreamResource.Name).
		SubResource("status").
		Body(imagestreamResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the imagestreamResource and deletes it. Returns an error if one occurs.
func (c *imagestreamResources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagestreamresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imagestreamResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagestreamresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched imagestreamResource.
func (c *imagestreamResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImagestreamResource, err error) {
	result = &v1alpha1.ImagestreamResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagestreamresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
